include $(CLEAR_VARS)
# ./configure --build=x86_64-pc-linux-gnu --host=arm-linux-eabi
# find $(GEOS_PATH)/ -name "*.cpp" | grep -Ev "tests|doc" | sort | awk '{ print "\t"$1" \\" }'
LOCAL_MODULE := geos
LOCAL_C_INCLUDES := $(GEOS_PATH)/source/headers
LOCAL_CFLAGS := $(LOCAL_C_INCLUDES:%=-I%) -DHAVE_LONG_LONG_INT_64
LOCAL_SRC_FILES := \
        $(GEOS_PATH)/capi/geos_c.cpp \
        $(GEOS_PATH)/capi/geos_ts_c.cpp \
        $(GEOS_PATH)/source/algorithm/Angle.cpp \
        $(GEOS_PATH)/source/algorithm/BoundaryNodeRule.cpp \
        $(GEOS_PATH)/source/algorithm/CentroidArea.cpp \
        $(GEOS_PATH)/source/algorithm/CentroidLine.cpp \
        $(GEOS_PATH)/source/algorithm/CentroidPoint.cpp \
        $(GEOS_PATH)/source/algorithm/CGAlgorithms.cpp \
        $(GEOS_PATH)/source/algorithm/ConvexHull.cpp \
        $(GEOS_PATH)/source/algorithm/distance/DiscreteHausdorffDistance.cpp \
        $(GEOS_PATH)/source/algorithm/distance/DistanceToPoint.cpp \
        $(GEOS_PATH)/source/algorithm/HCoordinate.cpp \
        $(GEOS_PATH)/source/algorithm/InteriorPointArea.cpp \
        $(GEOS_PATH)/source/algorithm/InteriorPointLine.cpp \
        $(GEOS_PATH)/source/algorithm/InteriorPointPoint.cpp \
        $(GEOS_PATH)/source/algorithm/LineIntersector.cpp \
        $(GEOS_PATH)/source/algorithm/locate/IndexedPointInAreaLocator.cpp \
        $(GEOS_PATH)/source/algorithm/locate/PointOnGeometryLocator.cpp \
        $(GEOS_PATH)/source/algorithm/locate/SimplePointInAreaLocator.cpp \
        $(GEOS_PATH)/source/algorithm/MCPointInRing.cpp \
        $(GEOS_PATH)/source/algorithm/MinimumDiameter.cpp \
        $(GEOS_PATH)/source/algorithm/NotRepresentableException.cpp \
        $(GEOS_PATH)/source/algorithm/PointLocator.cpp \
        $(GEOS_PATH)/source/algorithm/RayCrossingCounter.cpp \
        $(GEOS_PATH)/source/algorithm/RobustDeterminant.cpp \
        $(GEOS_PATH)/source/algorithm/SimplePointInRing.cpp \
        $(GEOS_PATH)/source/algorithm/SIRtreePointInRing.cpp \
        $(GEOS_PATH)/source/geom/CoordinateArraySequence.cpp \
        $(GEOS_PATH)/source/geom/CoordinateArraySequenceFactory.cpp \
        $(GEOS_PATH)/source/geom/Coordinate.cpp \
        $(GEOS_PATH)/source/geom/CoordinateSequence.cpp \
        $(GEOS_PATH)/source/geom/CoordinateSequenceFactory.cpp \
        $(GEOS_PATH)/source/geom/Dimension.cpp \
        $(GEOS_PATH)/source/geom/Envelope.cpp \
        $(GEOS_PATH)/source/geom/GeometryCollection.cpp \
        $(GEOS_PATH)/source/geom/GeometryComponentFilter.cpp \
        $(GEOS_PATH)/source/geom/Geometry.cpp \
        $(GEOS_PATH)/source/geom/GeometryFactory.cpp \
        $(GEOS_PATH)/source/geom/GeometryList.cpp \
        $(GEOS_PATH)/source/geomgraph/Depth.cpp \
        $(GEOS_PATH)/source/geomgraph/DirectedEdge.cpp \
        $(GEOS_PATH)/source/geomgraph/DirectedEdgeStar.cpp \
        $(GEOS_PATH)/source/geomgraph/Edge.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeEnd.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeEndStar.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeIntersection.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeIntersectionList.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeList.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeNodingValidator.cpp \
        $(GEOS_PATH)/source/geomgraph/EdgeRing.cpp \
        $(GEOS_PATH)/source/geomgraph/GeometryGraph.cpp \
        $(GEOS_PATH)/source/geomgraph/GraphComponent.cpp \
        $(GEOS_PATH)/source/geomgraph/index/MonotoneChainEdge.cpp \
        $(GEOS_PATH)/source/geomgraph/index/MonotoneChainIndexer.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SegmentIntersector.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SimpleEdgeSetIntersector.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SimpleMCSweepLineIntersector.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SimpleSweepLineIntersector.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SweepLineEvent.cpp \
        $(GEOS_PATH)/source/geomgraph/index/SweepLineSegment.cpp \
        $(GEOS_PATH)/source/geomgraph/Label.cpp \
        $(GEOS_PATH)/source/geomgraph/Node.cpp \
        $(GEOS_PATH)/source/geomgraph/NodeFactory.cpp \
        $(GEOS_PATH)/source/geomgraph/NodeMap.cpp \
        $(GEOS_PATH)/source/geomgraph/PlanarGraph.cpp \
        $(GEOS_PATH)/source/geomgraph/Position.cpp \
        $(GEOS_PATH)/source/geomgraph/Quadrant.cpp \
        $(GEOS_PATH)/source/geomgraph/TopologyLocation.cpp \
        $(GEOS_PATH)/source/geom/IntersectionMatrix.cpp \
        $(GEOS_PATH)/source/geom/LinearRing.cpp \
        $(GEOS_PATH)/source/geom/LineSegment.cpp \
        $(GEOS_PATH)/source/geom/LineString.cpp \
        $(GEOS_PATH)/source/geom/Location.cpp \
        $(GEOS_PATH)/source/geom/MultiLineString.cpp \
        $(GEOS_PATH)/source/geom/MultiPoint.cpp \
        $(GEOS_PATH)/source/geom/MultiPolygon.cpp \
        $(GEOS_PATH)/source/geom/Point.cpp \
        $(GEOS_PATH)/source/geom/Polygon.cpp \
        $(GEOS_PATH)/source/geom/PrecisionModel.cpp \
        $(GEOS_PATH)/source/geom/prep/AbstractPreparedPolygonContains.cpp \
        $(GEOS_PATH)/source/geom/prep/BasicPreparedGeometry.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedGeometry.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedGeometryFactory.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedLineString.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedLineStringIntersects.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPoint.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygonContains.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygonContainsProperly.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygonCovers.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygon.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygonIntersects.cpp \
        $(GEOS_PATH)/source/geom/prep/PreparedPolygonPredicate.cpp \
        $(GEOS_PATH)/source/geom/Triangle.cpp \
        $(GEOS_PATH)/source/geom/util/ComponentCoordinateExtracter.cpp \
        $(GEOS_PATH)/source/geom/util/CoordinateOperation.cpp \
        $(GEOS_PATH)/source/geom/util/GeometryCombiner.cpp \
        $(GEOS_PATH)/source/geom/util/GeometryEditor.cpp \
        $(GEOS_PATH)/source/geom/util/GeometryTransformer.cpp \
        $(GEOS_PATH)/source/geom/util/ShortCircuitedGeometryVisitor.cpp \
        $(GEOS_PATH)/source/index/bintree/Bintree.cpp \
        $(GEOS_PATH)/source/index/bintree/Interval.cpp \
        $(GEOS_PATH)/source/index/bintree/Key.cpp \
        $(GEOS_PATH)/source/index/bintree/NodeBase.cpp \
        $(GEOS_PATH)/source/index/bintree/Node.cpp \
        $(GEOS_PATH)/source/index/bintree/Root.cpp \
        $(GEOS_PATH)/source/index/chain/MonotoneChainBuilder.cpp \
        $(GEOS_PATH)/source/index/chain/MonotoneChain.cpp \
        $(GEOS_PATH)/source/index/chain/MonotoneChainOverlapAction.cpp \
        $(GEOS_PATH)/source/index/chain/MonotoneChainSelectAction.cpp \
        $(GEOS_PATH)/source/index/intervalrtree/IntervalRTreeBranchNode.cpp \
        $(GEOS_PATH)/source/index/intervalrtree/IntervalRTreeLeafNode.cpp \
        $(GEOS_PATH)/source/index/intervalrtree/IntervalRTreeNode.cpp \
        $(GEOS_PATH)/source/index/intervalrtree/SortedPackedIntervalRTree.cpp \
        $(GEOS_PATH)/source/index/quadtree/DoubleBits.cpp \
        $(GEOS_PATH)/source/index/quadtree/IntervalSize.cpp \
        $(GEOS_PATH)/source/index/quadtree/Key.cpp \
        $(GEOS_PATH)/source/index/quadtree/NodeBase.cpp \
        $(GEOS_PATH)/source/index/quadtree/Node.cpp \
        $(GEOS_PATH)/source/index/quadtree/Quadtree.cpp \
        $(GEOS_PATH)/source/index/quadtree/Root.cpp \
        $(GEOS_PATH)/source/index/strtree/AbstractNode.cpp \
        $(GEOS_PATH)/source/index/strtree/AbstractSTRtree.cpp \
        $(GEOS_PATH)/source/index/strtree/Interval.cpp \
        $(GEOS_PATH)/source/index/strtree/ItemBoundable.cpp \
        $(GEOS_PATH)/source/index/strtree/SIRtree.cpp \
        $(GEOS_PATH)/source/index/strtree/STRtree.cpp \
        $(GEOS_PATH)/source/index/sweepline/SweepLineEvent.cpp \
        $(GEOS_PATH)/source/index/sweepline/SweepLineIndex.cpp \
        $(GEOS_PATH)/source/index/sweepline/SweepLineInterval.cpp \
        $(GEOS_PATH)/source/inlines.cpp \
        $(GEOS_PATH)/source/io/ByteOrderDataInStream.cpp \
        $(GEOS_PATH)/source/io/ByteOrderValues.cpp \
        $(GEOS_PATH)/source/io/CLocalizer.cpp \
        $(GEOS_PATH)/source/io/ParseException.cpp \
        $(GEOS_PATH)/source/io/StringTokenizer.cpp \
        $(GEOS_PATH)/source/io/Unload.cpp \
        $(GEOS_PATH)/source/io/WKBReader.cpp \
        $(GEOS_PATH)/source/io/WKBWriter.cpp \
        $(GEOS_PATH)/source/io/WKTReader.cpp \
        $(GEOS_PATH)/source/io/WKTWriter.cpp \
        $(GEOS_PATH)/source/io/Writer.cpp \
        $(GEOS_PATH)/source/linearref/ExtractLineByLocation.cpp \
        $(GEOS_PATH)/source/linearref/LengthIndexedLine.cpp \
        $(GEOS_PATH)/source/linearref/LengthIndexOfPoint.cpp \
        $(GEOS_PATH)/source/linearref/LengthLocationMap.cpp \
        $(GEOS_PATH)/source/linearref/LinearGeometryBuilder.cpp \
        $(GEOS_PATH)/source/linearref/LinearIterator.cpp \
        $(GEOS_PATH)/source/linearref/LinearLocation.cpp \
        $(GEOS_PATH)/source/linearref/LocationIndexOfLine.cpp \
        $(GEOS_PATH)/source/linearref/LocationIndexOfPoint.cpp \
        $(GEOS_PATH)/source/noding/BasicSegmentString.cpp \
        $(GEOS_PATH)/source/noding/FastNodingValidator.cpp \
        $(GEOS_PATH)/source/noding/FastSegmentSetIntersectionFinder.cpp \
        $(GEOS_PATH)/source/noding/IntersectionAdder.cpp \
        $(GEOS_PATH)/source/noding/IntersectionFinderAdder.cpp \
        $(GEOS_PATH)/source/noding/IteratedNoder.cpp \
        $(GEOS_PATH)/source/noding/MCIndexNoder.cpp \
        $(GEOS_PATH)/source/noding/MCIndexSegmentSetMutualIntersector.cpp \
        $(GEOS_PATH)/source/noding/NodedSegmentString.cpp \
        $(GEOS_PATH)/source/noding/NodingValidator.cpp \
        $(GEOS_PATH)/source/noding/Octant.cpp \
        $(GEOS_PATH)/source/noding/OrientedCoordinateArray.cpp \
        $(GEOS_PATH)/source/noding/ScaledNoder.cpp \
        $(GEOS_PATH)/source/noding/SegmentIntersectionDetector.cpp \
        $(GEOS_PATH)/source/noding/SegmentNode.cpp \
        $(GEOS_PATH)/source/noding/SegmentNodeList.cpp \
        $(GEOS_PATH)/source/noding/SegmentString.cpp \
        $(GEOS_PATH)/source/noding/SegmentStringUtil.cpp \
        $(GEOS_PATH)/source/noding/SimpleNoder.cpp \
        $(GEOS_PATH)/source/noding/SingleInteriorIntersectionFinder.cpp \
        $(GEOS_PATH)/source/noding/snapround/HotPixel.cpp \
        $(GEOS_PATH)/source/noding/snapround/MCIndexPointSnapper.cpp \
        $(GEOS_PATH)/source/noding/snapround/MCIndexSnapRounder.cpp \
        $(GEOS_PATH)/source/noding/snapround/SimpleSnapRounder.cpp \
        $(GEOS_PATH)/source/operation/buffer/BufferBuilder.cpp \
        $(GEOS_PATH)/source/operation/buffer/BufferInputLineSimplifier.cpp \
        $(GEOS_PATH)/source/operation/buffer/BufferOp.cpp \
        $(GEOS_PATH)/source/operation/buffer/BufferParameters.cpp \
        $(GEOS_PATH)/source/operation/buffer/BufferSubgraph.cpp \
        $(GEOS_PATH)/source/operation/buffer/OffsetCurveBuilder.cpp \
        $(GEOS_PATH)/source/operation/buffer/OffsetCurveSetBuilder.cpp \
        $(GEOS_PATH)/source/operation/buffer/RightmostEdgeFinder.cpp \
        $(GEOS_PATH)/source/operation/buffer/SubgraphDepthLocater.cpp \
        $(GEOS_PATH)/source/operation/distance/ConnectedElementLocationFilter.cpp \
        $(GEOS_PATH)/source/operation/distance/ConnectedElementPointFilter.cpp \
        $(GEOS_PATH)/source/operation/distance/DistanceOp.cpp \
        $(GEOS_PATH)/source/operation/distance/GeometryLocation.cpp \
        $(GEOS_PATH)/source/operation/GeometryGraphOperation.cpp \
        $(GEOS_PATH)/source/operation/IsSimpleOp.cpp \
        $(GEOS_PATH)/source/operation/linemerge/EdgeString.cpp \
        $(GEOS_PATH)/source/operation/linemerge/LineMergeDirectedEdge.cpp \
        $(GEOS_PATH)/source/operation/linemerge/LineMergeEdge.cpp \
        $(GEOS_PATH)/source/operation/linemerge/LineMergeGraph.cpp \
        $(GEOS_PATH)/source/operation/linemerge/LineMerger.cpp \
        $(GEOS_PATH)/source/operation/linemerge/LineSequencer.cpp \
        $(GEOS_PATH)/source/operation/overlay/EdgeSetNoder.cpp \
        $(GEOS_PATH)/source/operation/overlay/ElevationMatrixCell.cpp \
        $(GEOS_PATH)/source/operation/overlay/ElevationMatrix.cpp \
        $(GEOS_PATH)/source/operation/overlay/LineBuilder.cpp \
        $(GEOS_PATH)/source/operation/overlay/MaximalEdgeRing.cpp \
        $(GEOS_PATH)/source/operation/overlay/MinimalEdgeRing.cpp \
        $(GEOS_PATH)/source/operation/overlay/OverlayNodeFactory.cpp \
        $(GEOS_PATH)/source/operation/overlay/OverlayOp.cpp \
        $(GEOS_PATH)/source/operation/overlay/PointBuilder.cpp \
        $(GEOS_PATH)/source/operation/overlay/PolygonBuilder.cpp \
        $(GEOS_PATH)/source/operation/overlay/snap/GeometrySnapper.cpp \
        $(GEOS_PATH)/source/operation/overlay/snap/LineStringSnapper.cpp \
        $(GEOS_PATH)/source/operation/overlay/snap/SnapIfNeededOverlayOp.cpp \
        $(GEOS_PATH)/source/operation/overlay/snap/SnapOverlayOp.cpp \
        $(GEOS_PATH)/source/operation/overlay/validate/FuzzyPointLocator.cpp \
        $(GEOS_PATH)/source/operation/overlay/validate/OffsetPointGenerator.cpp \
        $(GEOS_PATH)/source/operation/overlay/validate/OverlayResultValidator.cpp \
        $(GEOS_PATH)/source/operation/polygonize/EdgeRing.cpp \
        $(GEOS_PATH)/source/operation/polygonize/PolygonizeDirectedEdge.cpp \
        $(GEOS_PATH)/source/operation/polygonize/PolygonizeEdge.cpp \
        $(GEOS_PATH)/source/operation/polygonize/PolygonizeGraph.cpp \
        $(GEOS_PATH)/source/operation/polygonize/Polygonizer.cpp \
        $(GEOS_PATH)/source/operation/predicate/RectangleContains.cpp \
        $(GEOS_PATH)/source/operation/predicate/RectangleIntersects.cpp \
        $(GEOS_PATH)/source/operation/predicate/SegmentIntersectionTester.cpp \
        $(GEOS_PATH)/source/operation/relate/EdgeEndBuilder.cpp \
        $(GEOS_PATH)/source/operation/relate/EdgeEndBundle.cpp \
        $(GEOS_PATH)/source/operation/relate/EdgeEndBundleStar.cpp \
        $(GEOS_PATH)/source/operation/relate/RelateComputer.cpp \
        $(GEOS_PATH)/source/operation/relate/RelateNode.cpp \
        $(GEOS_PATH)/source/operation/relate/RelateNodeFactory.cpp \
        $(GEOS_PATH)/source/operation/relate/RelateNodeGraph.cpp \
        $(GEOS_PATH)/source/operation/relate/RelateOp.cpp \
        $(GEOS_PATH)/source/operation/union/CascadedPolygonUnion.cpp \
        $(GEOS_PATH)/source/operation/valid/ConnectedInteriorTester.cpp \
        $(GEOS_PATH)/source/operation/valid/ConsistentAreaTester.cpp \
        $(GEOS_PATH)/source/operation/valid/IndexedNestedRingTester.cpp \
        $(GEOS_PATH)/source/operation/valid/IsValidOp.cpp \
        $(GEOS_PATH)/source/operation/valid/QuadtreeNestedRingTester.cpp \
        $(GEOS_PATH)/source/operation/valid/RepeatedPointTester.cpp \
        $(GEOS_PATH)/source/operation/valid/SimpleNestedRingTester.cpp \
        $(GEOS_PATH)/source/operation/valid/SweeplineNestedRingTester.cpp \
        $(GEOS_PATH)/source/operation/valid/TopologyValidationError.cpp \
        $(GEOS_PATH)/source/planargraph/algorithm/ConnectedSubgraphFinder.cpp \
        $(GEOS_PATH)/source/planargraph/DirectedEdge.cpp \
        $(GEOS_PATH)/source/planargraph/DirectedEdgeStar.cpp \
        $(GEOS_PATH)/source/planargraph/Edge.cpp \
        $(GEOS_PATH)/source/planargraph/Node.cpp \
        $(GEOS_PATH)/source/planargraph/NodeMap.cpp \
        $(GEOS_PATH)/source/planargraph/PlanarGraph.cpp \
        $(GEOS_PATH)/source/planargraph/Subgraph.cpp \
        $(GEOS_PATH)/source/precision/CommonBits.cpp \
        $(GEOS_PATH)/source/precision/CommonBitsOp.cpp \
        $(GEOS_PATH)/source/precision/CommonBitsRemover.cpp \
        $(GEOS_PATH)/source/precision/EnhancedPrecisionOp.cpp \
        $(GEOS_PATH)/source/precision/SimpleGeometryPrecisionReducer.cpp \
        $(GEOS_PATH)/source/simplify/DouglasPeuckerLineSimplifier.cpp \
        $(GEOS_PATH)/source/simplify/DouglasPeuckerSimplifier.cpp \
        $(GEOS_PATH)/source/simplify/LineSegmentIndex.cpp \
        $(GEOS_PATH)/source/simplify/TaggedLineSegment.cpp \
        $(GEOS_PATH)/source/simplify/TaggedLinesSimplifier.cpp \
        $(GEOS_PATH)/source/simplify/TaggedLineString.cpp \
        $(GEOS_PATH)/source/simplify/TaggedLineStringSimplifier.cpp \
        $(GEOS_PATH)/source/simplify/TopologyPreservingSimplifier.cpp \
        $(GEOS_PATH)/source/util/Assert.cpp \
        $(GEOS_PATH)/source/util/GeometricShapeFactory.cpp \
        $(GEOS_PATH)/source/util/math.cpp \
        $(GEOS_PATH)/source/util/Profiler.cpp
include $(BUILD_STATIC_LIBRARY)