/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.OGR {

public enum FieldSubType {
  OFSTNone = 0,
  OFSTBoolean = 1,
  OFSTInt16 = 2,
  OFSTFloat32 = 3
}

}
