/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.OGR {

public enum wkbGeometryType {
  wkbUnknown = 0,
  wkbPoint = 1,
  wkbLineString = 2,
  wkbPolygon = 3,
  wkbMultiPoint = 4,
  wkbMultiLineString = 5,
  wkbMultiPolygon = 6,
  wkbGeometryCollection = 7,
  wkbCircularString = 8,
  wkbCompoundCurve = 9,
  wkbCurvePolygon = 10,
  wkbMultiCurve = 11,
  wkbMultiSurface = 12,
  wkbNone = 100,
  wkbLinearRing = 101,
  wkbCircularStringZ = 1008,
  wkbCompoundCurveZ = 1009,
  wkbCurvePolygonZ = 1010,
  wkbMultiCurveZ = 1011,
  wkbMultiSurfaceZ = 1012,
  wkbPoint25D = -2147483647,
  wkbLineString25D = -2147483646,
  wkbPolygon25D = -2147483645,
  wkbMultiPoint25D = -2147483644,
  wkbMultiLineString25D = -2147483643,
  wkbMultiPolygon25D = -2147483642,
  wkbGeometryCollection25D = -2147483641
}

}
