/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OSGeo.GDAL {

public enum RIOResampleAlg {
  GRIORA_NearestNeighbour = 0,
  GRIORA_Bilinear = 1,
  GRIORA_Cubic = 2,
  GRIORA_CubicSpline = 3,
  GRIORA_Lanczos = 4,
  GRIORA_Average = 5,
  GRIORA_Mode = 6,
  GRIORA_Gauss = 7
}

}
